### PR TITLE
Support long durations experiments

### PR DESCRIPTION
**Pull request by kswenson**
Support long durations experiments [#157414537]
- down-sample long-running experiments

### CODE REVIEW

**Comment by scytacki** [comment]
This code looks good to me.  I assume you reviewed this down sampling approach with Dan?
I can think up various problems with this approach, but it should work well in most cases. So if Dan is fine with it, then it is fine with me.

An example problem would be an experiment with a spring on a force sensor.  If it starts oscillating about the same rate as finally downsampling, the oscillation will get lost or mis represented. A better down sampling (I think) would either average (so it doesn't show incorrect data), or would show both the min and max of the samples that is converting.  I'm not sure if CODAP has a graph can nicely represent a min and max y for the same x value.  I  suppose another option is to randomly select the y value in each downsampled set.  This would prevent showing an incorrect oscillation in the case above. 

Another example is a force sensor collision experiment.  The might only be one point with the max force.  Taking the first point, averaging, or random point selection are all likely to hide this spike. The min max would show it.

**Comment by ddamelin** [comment]
We have been discussing this. There might be a better way to smooth the data rather than pick specific points, but for now this works well. See attached graphs. 
untitled_document_-_codap-2

**Comment by kswenson** [comment]
I added a PT story for consideration of alternate down-sampling methods: https://www.pivotaltracker.com/story/show/157441208.

**Comment by scytacki** [comment]
Yes those graphs work well. The problem cases that I mentioned above might be rare. Here are some specific theoretical cases.  Assuming 10samples/second.
- oscillations with a period around 3s or less when the full data is viewed could look flat, or could look like they have a much longer period.
- sub 1s impulses. \\

**Comment by scytacki** [comment]
But the sensor interactive graph shows the whole data set right?  So this will provide a hint that something interesting is going on. And could be a great learning point for students.

**Comment by scytacki** [comment]
Yes I agree.

**Pull request merged**
